In [2]:
import numpy as np
items=range(10,51,10)
arr=np.array(items)
print(arr)
print(arr.shape)

[10 20 30 40 50]
(5,)


In [3]:
items2=[range(1,6),range(10,51,10)]
arr2=np.array(items2)
print(arr)
print(arr.shape)

[10 20 30 40 50]
(5,)


In [6]:
ar1=[[70,80],[195,185]]
ar2=[[50,60],[70,80]]
print(ar1+ar2)
print(ar1-ar2)
print(ar1*ar2)
print(ar1/ar2)
print(ar1//ar2)

[[70, 80], [195, 185], [50, 60], [70, 80]]


TypeError: can't multiply sequence by non-int of type 'list'

In [7]:
student1=[60,70,80]
student2=[77,88,99]
points=np.array([student1,student2])
print(points)

[[60 70 80]
 [77 88 99]]


In [8]:
print(points.sum())
print(points.sum(axis=0))
print(points.sum(axis=1))
print(points.mean())
print(points.mean(axis=0))
print(points.mean(axis=1))

474
[137 158 179]
[210 264]
79.0
[68.5 79.  89.5]
[70. 88.]


In [9]:
arr=np.maximum(student1,student2)
print(arr)

[77 88 99]


In [10]:
print(arr.sum())
print(arr.mean())

264
88.0


In [11]:
print(np.sort(arr))
print(np.sort(arr)[::-1])

[77 88 99]
[99 88 77]


In [12]:
names=np.array(['김철수','이승호','김철수','김철수','홍상현','이영희','윤동주'])
ages=np.array([20,35,30,33,38,39,30,31,30,40,45])
print(np.unique(names))
print(np.unique(ages))

['김철수' '윤동주' '이승호' '이영희' '홍상현']
[20 30 31 33 35 38 39 40 45]
