In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.7.0'

In [4]:
tf.config.list_physical_devices('GPU')

[]

In [5]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 2865531846643175228
 xla_global_id: -1]

In [6]:
tf.debugging.set_log_device_placement(True)
a=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
b=tf.constant([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
c=tf.matmul(a,b)
print(c)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op MatMul in device /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [7]:
tf.debugging.set_log_device_placement(True)
with tf.device('/CPU:0'):
    a=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
    b=tf.constant([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
    c=tf.matmul(a,b)
    print(c)

Executing op MatMul in device /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [8]:
tf.debugging.set_log_device_placement(True)
with tf.device('/GPU:0'):
    a=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
    b=tf.constant([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
    c=tf.matmul(a,b)
    print(c)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op MatMul in device /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [1]:
import tensorflow as tf
import sys
print(sys.version)
print(tf.__version__)

3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
2.7.0


In [2]:
hello=tf.constant('Hello World')
print(hello)
print(hello.numpy())
print(hello.numpy().decode('utf-8'))
a=tf.constant(10)
b=tf.constant(32)
c=tf.add(a,b)
print(c.numpy())
print([a.numpy(),b.numpy(),c.numpy])

tf.Tensor(b'Hello World', shape=(), dtype=string)
b'Hello World'
Hello World
42
[10, 32, <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=42>>]


In [3]:
node1=tf.constant(3.0)
node2=tf.constant(4.0)
node3=tf.add(node1,node2)
print(node3.numpy())

7.0


In [4]:
def output(a,b):
    return tf.multiply(a, b)
print(output(3.0, 5.0).numpy())
print(output(0.0, 6.0).numpy())
print(output([2.0,3.1,7.4], [6.0,2.5,3.1]).numpy())


15.0
0.0
[12.    7.75 22.94]


In [5]:
W = tf.Variable([0.3], dtype=tf.float32)
b = tf.Variable([-0.3], dtype=tf.float32)
def linear_model(x):
    return tf.multiply(W,tf.add(x,b))
x=[1.,2.,3.,4.]
linear_model(x).numpy()

array([0.21000001, 0.51000005, 0.81000006, 1.11      ], dtype=float32)

In [6]:
import numpy as np
X = np.array([[1,2,3],[4,5,6]])
print('X\n',X)
W = np.array([[np.random.randint(10) for col in range(2)]
for row in range(3)])
print('W\n',W)
b = np.array([[np.random.randint(10) for col in range(1)]
for row in range(2)])
print('b\n',b)
def expr(X):
    return tf.matmul(X, W) +b
print('Result\n',expr(X).numpy())

X
 [[1 2 3]
 [4 5 6]]
W
 [[3 4]
 [1 0]
 [1 8]]
b
 [[3]
 [9]]
Result
 [[11 31]
 [32 73]]


In [7]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [8]:
def gugu(dan):
    left=tf.placeholder(tf.int32)
    right=tf.placeholder(tf.int32)
    calc=tf.multiply(left,right)
    
    with tf.Session() as sess:
        for i in range(1,10):
            result=sess.run(calc,feed_dict={left: dan,right: i})
            print("{0}x{1}={2:2}".format(dan, i,result))
gugu(7)

7x1= 7
7x2=14
7x3=21
7x4=28
7x5=35
7x6=42
7x7=49
7x8=56
7x9=63


In [1]:
import tensorflow as tf

def calc(left,right):
    return tf.multiply(left,right)

def gugu(dan):
    for i in range(1,10):
        result=calc(dan,i)
        print("{0}x{1}={2:2}".format(dan, i,result))
        
gugu(7)

7x1= 7
7x2=14
7x3=21
7x4=28
7x5=35
7x6=42
7x7=49
7x8=56
7x9=63
