In [1]:
text="""
경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n
그런 식으로 하면 말이 안된다\n
새로 태어난 말이 배가 고프다\n
"""

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer

t=Tokenizer()
t.fit_on_texts([text])
vocab_size=len(t.word_index)+1
print('단어 집합의 크기: %d' %vocab_size)

단어 집합의 크기: 20


In [3]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11, '그런': 12, '식으로': 13, '하면': 14, '안된다': 15, '새로': 16, '태어난': 17, '배가': 18, '고프다': 19}


In [4]:
sequences=list()
for line in text.split('\n'):
    encoded=t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence=encoded[:i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수: %d' % len(sequences))

학습에 사용할 샘플의 개수: 19


In [5]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11], [12, 13], [12, 13, 14], [12, 13, 14, 1], [12, 13, 14, 1, 15], [16, 17], [16, 17, 1], [16, 17, 1, 18], [16, 17, 1, 18, 19]]


In [6]:
max_len=max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 6


In [7]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
a=[[1,2,3],[4,5],[6,7,8,9]]
print(a)
b=pad_sequences(a)
print(b)
c=pad_sequences(a,padding='post')
print(c)
d=pad_sequences(a,padding='post',value=1)
print(d)
e=pad_sequences(a,padding='post',maxlen=3)
print(e)
e=pad_sequences(a,padding='post',maxlen=3,truncating='post')
print(e)

[[1, 2, 3], [4, 5], [6, 7, 8, 9]]
[[0 1 2 3]
 [0 0 4 5]
 [6 7 8 9]]
[[1 2 3 0]
 [4 5 0 0]
 [6 7 8 9]]
[[1 2 3 1]
 [4 5 1 1]
 [6 7 8 9]]
[[1 2 3]
 [4 5 0]
 [7 8 9]]
[[1 2 3]
 [4 5 0]
 [6 7 8]]


In [8]:
sequences=pad_sequences(sequences,maxlen=max_len,padding='pre')

In [9]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]
 [ 0  0  0  0 12 13]
 [ 0  0  0 12 13 14]
 [ 0  0 12 13 14  1]
 [ 0 12 13 14  1 15]
 [ 0  0  0  0 16 17]
 [ 0  0  0 16 17  1]
 [ 0  0 16 17  1 18]
 [ 0 16 17  1 18 19]]


In [10]:
import numpy as np

sequences=np.array(sequences)
X=sequences[:,:-1]
y=sequences[:,-1]

In [11]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]
 [ 0  0  0  0 12]
 [ 0  0  0 12 13]
 [ 0  0 12 13 14]
 [ 0 12 13 14  1]
 [ 0  0  0  0 16]
 [ 0  0  0 16 17]
 [ 0  0 16 17  1]
 [ 0 16 17  1 18]]


In [12]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11 13 14  1 15 17  1 18 19]


In [14]:
from tensorflow.keras import utils
y=utils.to_categorical(y, num_classes=vocab_size)

In [15]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.

In [16]:
max_len

6

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding, SimpleRNN

model=Sequential()
model.add(Embedding(vocab_size,10,input_length=max_len-1))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [18]:
model.fit(X,y,epochs=200, verbose=2)

Epoch 1/200
1/1 - 1s - loss: 2.9819 - accuracy: 0.0526
Epoch 2/200
1/1 - 0s - loss: 2.9689 - accuracy: 0.1579
Epoch 3/200
1/1 - 0s - loss: 2.9557 - accuracy: 0.2632
Epoch 4/200
1/1 - 0s - loss: 2.9423 - accuracy: 0.3158
Epoch 5/200
1/1 - 0s - loss: 2.9286 - accuracy: 0.3158
Epoch 6/200
1/1 - 0s - loss: 2.9144 - accuracy: 0.3158
Epoch 7/200
1/1 - 0s - loss: 2.8996 - accuracy: 0.3158
Epoch 8/200
1/1 - 0s - loss: 2.8841 - accuracy: 0.3158
Epoch 9/200
1/1 - 0s - loss: 2.8679 - accuracy: 0.3158
Epoch 10/200
1/1 - 0s - loss: 2.8509 - accuracy: 0.3158
Epoch 11/200
1/1 - 0s - loss: 2.8329 - accuracy: 0.3158
Epoch 12/200
1/1 - 0s - loss: 2.8140 - accuracy: 0.3158
Epoch 13/200
1/1 - 0s - loss: 2.7941 - accuracy: 0.3158
Epoch 14/200
1/1 - 0s - loss: 2.7732 - accuracy: 0.3158
Epoch 15/200
1/1 - 0s - loss: 2.7514 - accuracy: 0.3158
Epoch 16/200
1/1 - 0s - loss: 2.7287 - accuracy: 0.3158
Epoch 17/200
1/1 - 0s - loss: 2.7051 - accuracy: 0.3158
Epoch 18/200
1/1 - 0s - loss: 2.6808 - accuracy: 0.3158
E

In [19]:
def sentence_generation(model, t, current_word, n):
    init_word=current_word
    sentence=''
    for _ in range(n):
        encoded=t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=max_len-1,padding='pre')
        pred=model.predict(encoded)
        result=np.argmax(pred,axis=1)
        for word, index in t.word_index.items():
            if index == result:
                break
        current_word=current_word + ' ' +word
        sentence=sentence + ' ' + word
    sentence=init_word + sentence
    return sentence

In [20]:
print(sentence_generation(model, t, '경마장에', 4)) 

경마장에 있는 말이 뛰고 있다


In [21]:
print(sentence_generation(model, t, '그의', 2)) 

그의 말이 법이다


In [22]:
print(sentence_generation(model, t, '가는', 5)) 
print(sentence_generation(model, t, '그런', 4)) 
print(sentence_generation(model, t, '새로', 4)) 

가는 말이 고와야 오는 말이 곱다
그런 말이 하면 말이 안된다
새로 태어난 말이 배가 고프다
